version: 2

project_name: athyr-agent

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/athyr-agent
    binary: athyr-agent
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/athyr-tech/athyr-agent/internal/cli.Version={{.Version}}
      - -X github.com/athyr-tech/athyr-agent/internal/cli.GitCommit={{.ShortCommit}}
      - -X github.com/athyr-tech/athyr-agent/internal/cli.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^test:"

brews:
  - name: athyr-agent
    repository:
      owner: athyr-tech
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://athyr.tech
    description: YAML-driven agent runner for Athyr
    license: MIT
    install: |
      bin.install "athyr-agent"
    test: |
      system bin/"athyr-agent", "version"

release:
  github:
    owner: athyr-tech
    name: athyr-agent
